application:
  name: spring-boot-undertow-http2
server:
  http2:
    enabled: true #Enable the SSL for webserver (undertow)
  port: 8443
  ssl: # TLS only needed for inbound HTTP/2 from browsers. Java11 TLS 1.3
    key-store: classpath:secure.jks
    key-store-password: secret
    key-password: secret
    enabled: true
    trust-store-password: secret
    trust-store-alias: turgay.dev
    trust-store-type: JKS
    key-store-type: JKS
    client-ssl-enabled: true

logging:
  config: classpath:log4j2.xml

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
