DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name  VARCHAR(250) NOT NULL,
    email      VARCHAR(250) DEFAULT NULL,
    salary     DECIMAL(20, 2) DEFAULT NULL,
    start_date DATE DEFAULT NULL
);
